name: EMD Benchmarks

on:
  pull_request_target:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate git for private-repo fetches
        run: |
            git config --global \
            url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf \
            "https://github.com/"
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1.2.0
        with:
          julia-version: "1"
