name: EMD Benchmarks

on:
  pull_request_target:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@v0.6
        with:
          julia-version: "1"
